### ISSUE TITLE
Please add ReSpeaker 4-Mic Array support!

### ISSUE THREAD

**Issue by oangelo** [respeaker/respeakerd#17]
sudo journalctl -f -u respeakerd
-- Logs begin at Thu 2019-02-14 08:11:59 -02. --
fev 24 20:21:40 jarvis respeakerd_safe[1321]: (24242ms)INFO  -- The source's negotiated info: name: alsa_input.platform-soc_sound.seeed-source, rate: 48000, format: float32le, channels:4, flat volume: 1  [pulse_collector_node.cc:404]
fev 24 20:21:40 jarvis respeakerd_safe[1321]: (24242ms)INFO  -- Initialize RingBuffer successed.   [pulse_collector_node.cc:426]
fev 24 20:21:40 jarvis respeakerd_safe[1321]: (24253ms)INFO  -- Connected to PulseAudio server.  [pulse_collector_node.cc:493]
fev 24 20:21:40 jarvis respeakerd_safe[1321]: (24253ms)INFO  -- PulseCollectorNode thread started.  [pulse_collector_node.cc:506]
fev 24 20:21:40 jarvis respeakerd_safe[1321]: (24253ms)ERROR -- VepAecBeamformingNode fail to read microphone config file, error[-1]: no such file.  [vep_aec_beamforming_node.cc:184]
fev 24 20:21:40 jarvis respeakerd_safe[1321]: (24254ms)INFO  -- PulseCollectorNode thread joined.  [pulse_collector_node.cc:635]
fev 24 20:21:40 jarvis respeakerd_safe[1321]: Can not start the respeaker node chain.
fev 24 20:21:40 jarvis respeakerd_safe[1321]: /usr/bin/respeakerd_safe, linha 88:  1355 Falha de segmentação  /usr/bin/respeakerd --source="${SOURCE}"
fev 24 20:21:40 jarvis systemd[1]: respeakerd.service: Main process exited, code=exited, status=139/n/a
fev 24 20:21:40 jarvis systemd[1]: respeakerd.service: Failed with result 'exit-code'.

**Comment by KillingJacky** [comment]
Hi @oangelo , since the ReSpeaker 4-Mic Array board has no output codec, it's hard to tune the algorithms to work perfectly, the AEC algorithm needs strict collaboration of the capture and playback codec. We decide not to support the 4-Mic Array with librespeaker after we've done many experiments.

**Comment by oangelo** [comment]
I see, thanks.
