### ISSUE TITLE
关于 bf 默认0通道

### ISSUE THREAD

**Issue by raiscui** [respeaker/respeakerd#6]
bf 默认0通道的时候, 或者 平时某一次 唤醒词触发后重新定位新bf后,  我在bf当前direction的 对面说唤醒词,为什么感觉唤醒几率没有下降? 我理解 bf 的处理不是会吧其他角度的音源消音吗?  为什么唤醒几率感觉哪个角度都没差别呢? 怎么做到的?

BTW: 我看到新的feature/respeakerd-snips 加了 不断变化的direction, 这应该和 respeaker array v2  的 效果类似吧,  这样感觉在一定情况下 (不太嘈杂吧) 有助于 唤醒词识别, 不过为啥目前的平时是固定direction的版本 个个角度 唤醒差不多? 我的错觉吗

**Comment by jerryyip** [comment]
你的理解是对的，但是在实际使用中，一方面bf不会把其他角度的音源完全消音（如果要完全消音，过多的非线性处理会使得音频损失一些特征，这对后面的ASR和KWS都是不利的），另一方面，如果你是在近场唤醒的话，唤醒率差距是不明显的。
