### ISSUE TITLE
无法点亮LED

### ISSUE THREAD

**Issue by CoorFun** [respeaker/respeakerd#7]
通过本库中`pixel_ring_server`所提供的方法控制LED，收到错误：
```
en = mraa.Gpio(12)
  File "/usr/lib/python2.7/dist-packages/mraa.py", line 755, in __init__
    this = _mraa.new_Gpio(pin, owner, raw)
ValueError: Invalid GPIO pin specified
```

尝试手动开启GPIO 12 也无济于事：
```
respeaker@salonval:/sys/class/gpio$ echo 12 > export
-bash: echo: write error: Invalid argument
```
尝试直接通过读写`/dev/spidev0.0` 设备文件控制spi，似乎存在冲突，LED点亮瞬间被关闭。

**Comment by CoorFun** [comment]
系统版本 lxqt

**Comment by CoorFun** [comment]
尝试了iot版本一样不行，无法读写GPIO12。。 

系统版本：
`Linux version 4.4.95-respeaker-r7 (root@server) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) ) #2 SMP Thu Mar 15 17:43:15 CST 2018`

**Comment by Pillar1989** [comment]
这个是老系统版本用了最新的mraa存在兼容性问题, 请升级到最新的系统https://v2.fangcloud.com/share/7395fd138a1cab496fd4792fe5?folder_id=188000311814&lang=en

**Comment by CoorFun** [comment]
谢谢，更新后问题解决。中文文档需要更新一下了~
