### ISSUE TITLE
Get source's info failed!

### ISSUE THREAD

**Issue by Stayer** [respeaker/respeakerd#8]
After running respeakerd with parameters 
`/usr/local/bin/respeakerd --snowboy_res_path=/usr/local/etc/respeakerd/resources/common.res --snowboy_model_path=/usr/local/etc/respeakerd/resources/snowboy.umdl --snowboy_sensitivity=0.4 --source=alsa_input.platform-sound_0.seeed-8ch` (as a systemctl service), and starting demo from Python folder, server will crash and report this:
```
Oct 04 20:59:59 v2 respeakerd_safe[7068]: (4499ms)INFO  -- pulseaudio context connecting...  [pulse_collector_node.cc:140]
Oct 04 20:59:59 v2 respeakerd_safe[7068]: (4505ms)INFO  -- pulseaudio context connected to the server.  [pulse_collector_node.cc:164]
Oct 04 20:59:59 v2 respeakerd_safe[7068]: (4505ms)INFO  -- The target source name: alsa_input.platform-sound_0.seeed-8ch  [pulse_collector_node.cc:167]
Oct 04 20:59:59 v2 respeakerd_safe[7068]: (4506ms)ERROR -- Get source's info failed!  [pulse_collector_node.cc:187]
Oct 04 20:59:59 v2 systemd[1]: respeakerd.service: Main process exited, code=exited, status=255/n/a
Oct 04 20:59:59 v2 systemd[1]: respeakerd.service: Unit entered failed state.
Oct 04 20:59:59 v2 systemd[1]: respeakerd.service: Failed with result 'exit-code'.
```

## Expected Behavior
Working demo

## Current Behavior
Crashed respeakerd

## Steps to Reproduce (for bugs)

1. run respeakerd
2. run `python demo_respeaker_v2_vep_alexa_with_light.py` or `python respeakerd_client.py`

## Your Environment (for bugs)
###a)
mraa - (https://github.com/respeaker/mraa) 16bb0ea89e04f5e58d994d51176710a802b9ab6e
respeakerd - (https://github.com/respeaker/respeakerd) fdc5bcde78666707f83d40dd8fba36129da90159

### b) librespeaker version:
2.0.0-build180720 armhf [installed]

### c) Python environment:
2.7.13

**Comment by KillingJacky** [comment]
@Stayer Thanks for reporting. From the error messages, the crashing happens at the very beginning, when respeakerd's querying PulseAudio for the device "alsa_input.platform-sound_0.seeed-8ch". It might be caused by some configuration change of the PulseAudio on your system. What's the output of the following commands on your system?
- `uname -a`
- `pactl list sources`

**Comment by Stayer** [comment]
I just change image to new (1st August) and now it works
